import type { IconType } from 'react-icons';
import {
  SiNodedotjs,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiDocker,
  SiPostgresql,
  SiMongodb,
  SiJest,
  SiGit,
  SiCplusplus,
  SiPython,
  SiStyledcomponents,
  SiFastify,
  SiRedis,
  SiSwagger,
  SiAxios,
  SiCheerio,
  SiAstro,
  SiGraphql,
  SiSonarqubeserver,
  SiFigma,
  SiHtml5,
  SiCss,
  SiApachemaven,
  SiSelenium,
  SiManjaro,
  SiNeovim,
  SiClaude,
  SiOpenjdk,
} from 'react-icons/si';
import { DiJava, DiAws } from 'react-icons/di';

const techIcons: Record<string, IconType> = {
  'Node.js': SiNodedotjs,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  React: SiReact,
  Docker: SiDocker,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Jest: SiJest,
  Git: SiGit,
  Java: DiJava,
  'C++': SiCplusplus,
  Python: SiPython,
  'Styled-Components': SiStyledcomponents,
  Fastify: SiFastify,
  Redis: SiRedis,
  Swagger: SiSwagger,
  Axios: SiAxios,
  Cheerio: SiCheerio,
  Astro: SiAstro,
  AWS: DiAws,
  GraphQL: SiGraphql,
  SonarQube: SiSonarqubeserver,
  Figma: SiFigma,
  HTML: SiHtml5,
  CSS: SiCss,
  Maven: SiApachemaven,
  Selenium: SiSelenium,
  'Manjaro Linux': SiManjaro,
  Neovim: SiNeovim,
  'Claude Code': SiClaude,
  OpenJDK: SiOpenjdk,
  Kiro: DiAws,
};

export function getTechIcon(name: string): IconType | undefined {
  return techIcons[name];
}
